name: horoscope
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_dotenv: ^5.0.2
  google_generative_ai: ^0.4.6
  flutter_gemini: ^3.0.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  intl: ^0.20.2
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  get: ^4.7.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - .env
