// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDvdGY9PKggIubQLHAW4lb5L6I_9dlK88',
    appId: '1:1043979143250:web:97885ff3009c78f932378b',
    messagingSenderId: '1043979143250',
    projectId: 'horoscope-new-9489b',
    authDomain: 'horoscope-new-9489b.firebaseapp.com',
    storageBucket: 'horoscope-new-9489b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6mNTR8CpbVtEUvyjh38bY9VvUybuHs1A',
    appId: '1:1043979143250:android:c4fef0c8485026db32378b',
    messagingSenderId: '1043979143250',
    projectId: 'horoscope-new-9489b',
    storageBucket: 'horoscope-new-9489b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr9EpyknzBOUlSIuPHKdjDTVsIw4EXGlw',
    appId: '1:1043979143250:ios:159c085dc85a05b932378b',
    messagingSenderId: '1043979143250',
    projectId: 'horoscope-new-9489b',
    storageBucket: 'horoscope-new-9489b.appspot.com',
    iosBundleId: 'com.example.horoscope',
  );
}
